/**
 * Regenerate migrations/0002_seed.sql from the content shipped in src/data, so the site
 * looks identical after the switch to D1:
 *
 *   bun scripts/gen-seed.ts
 *
 * Only for a fresh database: the migration inserts with fixed ids.
 */
import { writeFileSync } from "node:fs";
import { FALLBACK_SITE_DATA } from "../src/data/site-data";

const q = (v: string | number) => (typeof v === "number" ? String(v) : `'${v.replace(/'/g, "''")}'`);

const lines = [
  "-- Generated by scripts/gen-seed.ts from src/data/content.ts and images.ts. Do not edit by hand.",
  "",
];

FALLBACK_SITE_DATA.projects.forEach((p, i) => {
  const values = [p.id, p.slot, p.kind, p.src, p.width, p.height, p.alt, p.caption, p.category, p.services.join("\n"), 0, i + 1];
  lines.push(
    `INSERT INTO projects (id, slot, kind, src, width, height, alt, caption, category, services, hidden, position) VALUES (${values.map(q).join(", ")});`,
  );
});

const { contact, founder, mosaic } = FALLBACK_SITE_DATA;
const settings: [string, string][] = [
  ["phone", contact.phone],
  ["whatsapp", contact.whatsapp],
  ["email", contact.email],
  ["facebook", contact.facebook],
  ["founder_name", founder.name],
  ["founder_photo", ""],
  ["home_mosaic", JSON.stringify(mosaic)],
];
lines.push("");
for (const [key, value] of settings) {
  lines.push(`INSERT INTO settings (key, value) VALUES (${q(key)}, ${q(value)});`);
}

writeFileSync("migrations/0002_seed.sql", `${lines.join("\n")}\n`);
console.log(`Wrote ${FALLBACK_SITE_DATA.projects.length} projects and ${settings.length} settings.`);
