/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BenefitsOfSeamlessGuttersRouteImport } from './routes/benefits-of-seamless-gutters'
import { Route as ColourRangeRouteImport } from './routes/colour-range'
import { Route as CommercialIndustrialRouteImport } from './routes/commercial-industrial'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as WhySeamlessGuttersRouteImport } from './routes/why-seamless-gutters'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BenefitsOfSeamlessGuttersRoute =
  BenefitsOfSeamlessGuttersRouteImport.update({
    id: '/benefits-of-seamless-gutters',
    path: '/benefits-of-seamless-gutters',
    getParentRoute: () => rootRouteImport,
  } as any)
const ColourRangeRoute = ColourRangeRouteImport.update({
  id: '/colour-range',
  path: '/colour-range',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialIndustrialRoute = CommercialIndustrialRouteImport.update({
  id: '/commercial-industrial',
  path: '/commercial-industrial',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const WhySeamlessGuttersRoute = WhySeamlessGuttersRouteImport.update({
  id: '/why-seamless-gutters',
  path: '/why-seamless-gutters',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/benefits-of-seamless-gutters': typeof BenefitsOfSeamlessGuttersRoute
  '/colour-range': typeof ColourRangeRoute
  '/commercial-industrial': typeof CommercialIndustrialRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/why-seamless-gutters': typeof WhySeamlessGuttersRoute
  '/services/$slug': typeof ServicesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/benefits-of-seamless-gutters': typeof BenefitsOfSeamlessGuttersRoute
  '/colour-range': typeof ColourRangeRoute
  '/commercial-industrial': typeof CommercialIndustrialRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/why-seamless-gutters': typeof WhySeamlessGuttersRoute
  '/services/$slug': typeof ServicesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/benefits-of-seamless-gutters': typeof BenefitsOfSeamlessGuttersRoute
  '/colour-range': typeof ColourRangeRoute
  '/commercial-industrial': typeof CommercialIndustrialRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/why-seamless-gutters': typeof WhySeamlessGuttersRoute
  '/services/$slug': typeof ServicesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/benefits-of-seamless-gutters'
    | '/colour-range'
    | '/commercial-industrial'
    | '/contact'
    | '/projects'
    | '/why-seamless-gutters'
    | '/services/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/benefits-of-seamless-gutters'
    | '/colour-range'
    | '/commercial-industrial'
    | '/contact'
    | '/projects'
    | '/why-seamless-gutters'
    | '/services/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/benefits-of-seamless-gutters'
    | '/colour-range'
    | '/commercial-industrial'
    | '/contact'
    | '/projects'
    | '/why-seamless-gutters'
    | '/services/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BenefitsOfSeamlessGuttersRoute: typeof BenefitsOfSeamlessGuttersRoute
  ColourRangeRoute: typeof ColourRangeRoute
  CommercialIndustrialRoute: typeof CommercialIndustrialRoute
  ContactRoute: typeof ContactRoute
  ProjectsRoute: typeof ProjectsRoute
  WhySeamlessGuttersRoute: typeof WhySeamlessGuttersRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benefits-of-seamless-gutters': {
      id: '/benefits-of-seamless-gutters'
      path: '/benefits-of-seamless-gutters'
      fullPath: '/benefits-of-seamless-gutters'
      preLoaderRoute: typeof BenefitsOfSeamlessGuttersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colour-range': {
      id: '/colour-range'
      path: '/colour-range'
      fullPath: '/colour-range'
      preLoaderRoute: typeof ColourRangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial-industrial': {
      id: '/commercial-industrial'
      path: '/commercial-industrial'
      fullPath: '/commercial-industrial'
      preLoaderRoute: typeof CommercialIndustrialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-seamless-gutters': {
      id: '/why-seamless-gutters'
      path: '/why-seamless-gutters'
      fullPath: '/why-seamless-gutters'
      preLoaderRoute: typeof WhySeamlessGuttersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BenefitsOfSeamlessGuttersRoute: BenefitsOfSeamlessGuttersRoute,
  ColourRangeRoute: ColourRangeRoute,
  CommercialIndustrialRoute: CommercialIndustrialRoute,
  ContactRoute: ContactRoute,
  ProjectsRoute: ProjectsRoute,
  WhySeamlessGuttersRoute: WhySeamlessGuttersRoute,
  ServicesSlugRoute: ServicesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
