/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BenefitsOfSeamlessGuttersRouteImport } from './routes/benefits-of-seamless-gutters'
import { Route as CommercialIndustrialRouteImport } from './routes/commercial-industrial'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as WhySeamlessGuttersRouteImport } from './routes/why-seamless-gutters'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminHomeGridRouteImport } from './routes/admin.home-grid'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as AdminProjectsIndexRouteImport } from './routes/admin.projects.index'
import { Route as AdminProjectsIdRouteImport } from './routes/admin.projects.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BenefitsOfSeamlessGuttersRoute =
  BenefitsOfSeamlessGuttersRouteImport.update({
    id: '/benefits-of-seamless-gutters',
    path: '/benefits-of-seamless-gutters',
    getParentRoute: () => rootRouteImport,
  } as any)
const CommercialIndustrialRoute = CommercialIndustrialRouteImport.update({
  id: '/commercial-industrial',
  path: '/commercial-industrial',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const WhySeamlessGuttersRoute = WhySeamlessGuttersRouteImport.update({
  id: '/why-seamless-gutters',
  path: '/why-seamless-gutters',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHomeGridRoute = AdminHomeGridRouteImport.update({
  id: '/admin/home-grid',
  path: '/admin/home-grid',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsIndexRoute = AdminProjectsIndexRouteImport.update({
  id: '/admin/projects/',
  path: '/admin/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsIdRoute = AdminProjectsIdRouteImport.update({
  id: '/admin/projects/$id',
  path: '/admin/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/benefits-of-seamless-gutters': typeof BenefitsOfSeamlessGuttersRoute
  '/commercial-industrial': typeof CommercialIndustrialRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/why-seamless-gutters': typeof WhySeamlessGuttersRoute
  '/admin/home-grid': typeof AdminHomeGridRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/projects/$id': typeof AdminProjectsIdRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/benefits-of-seamless-gutters': typeof BenefitsOfSeamlessGuttersRoute
  '/commercial-industrial': typeof CommercialIndustrialRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/why-seamless-gutters': typeof WhySeamlessGuttersRoute
  '/admin/home-grid': typeof AdminHomeGridRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/projects/$id': typeof AdminProjectsIdRoute
  '/admin/projects': typeof AdminProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/benefits-of-seamless-gutters': typeof BenefitsOfSeamlessGuttersRoute
  '/commercial-industrial': typeof CommercialIndustrialRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/why-seamless-gutters': typeof WhySeamlessGuttersRoute
  '/admin/home-grid': typeof AdminHomeGridRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/projects/$id': typeof AdminProjectsIdRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/benefits-of-seamless-gutters'
    | '/commercial-industrial'
    | '/contact'
    | '/projects'
    | '/why-seamless-gutters'
    | '/admin/home-grid'
    | '/admin/login'
    | '/admin/settings'
    | '/services/$slug'
    | '/admin/'
    | '/admin/projects/$id'
    | '/admin/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/benefits-of-seamless-gutters'
    | '/commercial-industrial'
    | '/contact'
    | '/projects'
    | '/why-seamless-gutters'
    | '/admin/home-grid'
    | '/admin/login'
    | '/admin/settings'
    | '/services/$slug'
    | '/admin'
    | '/admin/projects/$id'
    | '/admin/projects'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/benefits-of-seamless-gutters'
    | '/commercial-industrial'
    | '/contact'
    | '/projects'
    | '/why-seamless-gutters'
    | '/admin/home-grid'
    | '/admin/login'
    | '/admin/settings'
    | '/services/$slug'
    | '/admin/'
    | '/admin/projects/$id'
    | '/admin/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BenefitsOfSeamlessGuttersRoute: typeof BenefitsOfSeamlessGuttersRoute
  CommercialIndustrialRoute: typeof CommercialIndustrialRoute
  ContactRoute: typeof ContactRoute
  ProjectsRoute: typeof ProjectsRoute
  WhySeamlessGuttersRoute: typeof WhySeamlessGuttersRoute
  AdminHomeGridRoute: typeof AdminHomeGridRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProjectsIdRoute: typeof AdminProjectsIdRoute
  AdminProjectsIndexRoute: typeof AdminProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benefits-of-seamless-gutters': {
      id: '/benefits-of-seamless-gutters'
      path: '/benefits-of-seamless-gutters'
      fullPath: '/benefits-of-seamless-gutters'
      preLoaderRoute: typeof BenefitsOfSeamlessGuttersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial-industrial': {
      id: '/commercial-industrial'
      path: '/commercial-industrial'
      fullPath: '/commercial-industrial'
      preLoaderRoute: typeof CommercialIndustrialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-seamless-gutters': {
      id: '/why-seamless-gutters'
      path: '/why-seamless-gutters'
      fullPath: '/why-seamless-gutters'
      preLoaderRoute: typeof WhySeamlessGuttersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/home-grid': {
      id: '/admin/home-grid'
      path: '/admin/home-grid'
      fullPath: '/admin/home-grid'
      preLoaderRoute: typeof AdminHomeGridRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects/': {
      id: '/admin/projects/'
      path: '/admin/projects'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AdminProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects/$id': {
      id: '/admin/projects/$id'
      path: '/admin/projects/$id'
      fullPath: '/admin/projects/$id'
      preLoaderRoute: typeof AdminProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BenefitsOfSeamlessGuttersRoute: BenefitsOfSeamlessGuttersRoute,
  CommercialIndustrialRoute: CommercialIndustrialRoute,
  ContactRoute: ContactRoute,
  ProjectsRoute: ProjectsRoute,
  WhySeamlessGuttersRoute: WhySeamlessGuttersRoute,
  AdminHomeGridRoute: AdminHomeGridRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminProjectsIdRoute: AdminProjectsIdRoute,
  AdminProjectsIndexRoute: AdminProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
